# Copyright 2025 LiveKit, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""HMAC-SHA1 signature utility for Tencent Cloud API authentication."""

from __future__ import annotations

import base64
import hashlib
import hmac
import urllib.parse


def _urlencode(value: str) -> str:
    """URL encode a string, ensuring + and = are encoded."""
    return urllib.parse.quote(value, safe="")


def generate_asr_signature(
    secret_key: str,
    appid: str | int,
    secret_id: str,
    timestamp: int,
    expired: int,
    nonce: int,
    params: dict[str, str | int | bool],
) -> str:
    """
    Generate HMAC-SHA1 signature for Tencent Cloud ASR WebSocket API.

    The signature is generated by:
    1. Sorting all parameters (except signature) alphabetically
    2. Concatenating into a query string
    3. Prepending the domain path
    4. Applying HMAC-SHA1 with SecretKey
    5. Base64 encoding
    6. URL encoding

    Args:
        secret_key: Tencent Cloud SecretKey
        appid: Tencent Cloud AppID
        secret_id: Tencent Cloud SecretID
        timestamp: Current UNIX timestamp in seconds
        expired: Expiration UNIX timestamp in seconds
        nonce: Random positive integer
        params: Additional query parameters (engine_model_type, voice_format, etc.)

    Returns:
        URL-encoded signature string
    """
    all_params = {
        "secretid": secret_id,
        "timestamp": str(timestamp),
        "expired": str(expired),
        "nonce": str(nonce),
    }

    for key, value in params.items():
        all_params[key] = str(value)

    sorted_params = sorted(all_params.items(), key=lambda x: x[0])
    query_string = "&".join(f"{k}={v}" for k, v in sorted_params)

    sign_string = f"asr.cloud.tencent.com/asr/v2/{appid}?{query_string}"

    hmac_obj = hmac.new(
        secret_key.encode("utf-8"),
        sign_string.encode("utf-8"),
        hashlib.sha1,
    )
    signature = base64.b64encode(hmac_obj.digest()).decode("utf-8")

    return _urlencode(signature)


def generate_tts_signature(
    secret_key: str,
    secret_id: str,
    timestamp: int,
    expired: int,
    params: dict[str, str | int | bool],
) -> str:
    """
    Generate HMAC-SHA1 signature for Tencent Cloud TTS WebSocket API.

    The signature is generated by:
    1. Sorting all parameters (except signature) alphabetically
    2. Concatenating into a query string
    3. Prepending "GET" + domain path
    4. Applying HMAC-SHA1 with SecretKey
    5. Base64 encoding
    6. URL encoding

    Args:
        secret_key: Tencent Cloud SecretKey
        secret_id: Tencent Cloud SecretID
        timestamp: Current UNIX timestamp in seconds
        expired: Expiration UNIX timestamp in seconds
        params: Additional query parameters (Action, AppId, VoiceType, etc.)

    Returns:
        URL-encoded signature string
    """
    all_params = {
        "SecretId": secret_id,
        "Timestamp": str(timestamp),
        "Expired": str(expired),
    }

    for key, value in params.items():
        all_params[key] = str(value)

    sorted_params = sorted(all_params.items(), key=lambda x: x[0])
    query_string = "&".join(f"{k}={v}" for k, v in sorted_params)

    sign_string = f"GETtts.cloud.tencent.com/stream_wsv2?{query_string}"

    hmac_obj = hmac.new(
        secret_key.encode("utf-8"),
        sign_string.encode("utf-8"),
        hashlib.sha1,
    )
    signature = base64.b64encode(hmac_obj.digest()).decode("utf-8")

    return _urlencode(signature)


def build_asr_url(
    appid: str | int,
    secret_id: str,
    timestamp: int,
    expired: int,
    nonce: int,
    signature: str,
    params: dict[str, str | int | bool],
) -> str:
    """
    Build the complete ASR WebSocket URL with all query parameters.

    Args:
        appid: Tencent Cloud AppID
        secret_id: Tencent Cloud SecretID
        timestamp: Current UNIX timestamp
        expired: Expiration UNIX timestamp
        nonce: Random positive integer
        signature: URL-encoded signature
        params: Additional query parameters

    Returns:
        Complete WebSocket URL
    """
    all_params = {
        "secretid": secret_id,
        "timestamp": str(timestamp),
        "expired": str(expired),
        "nonce": str(nonce),
        "signature": signature,
    }

    for key, value in params.items():
        all_params[key] = str(value)

    sorted_params = sorted(all_params.items(), key=lambda x: x[0])
    query_string = "&".join(f"{k}={v}" for k, v in sorted_params)

    return f"wss://asr.cloud.tencent.com/asr/v2/{appid}?{query_string}"


def build_tts_url(
    secret_id: str,
    timestamp: int,
    expired: int,
    signature: str,
    params: dict[str, str | int | bool],
) -> str:
    """
    Build the complete TTS WebSocket URL with all query parameters.

    Args:
        secret_id: Tencent Cloud SecretID
        timestamp: Current UNIX timestamp
        expired: Expiration UNIX timestamp
        signature: URL-encoded signature
        params: Additional query parameters

    Returns:
        Complete WebSocket URL
    """
    all_params = {
        "SecretId": secret_id,
        "Timestamp": str(timestamp),
        "Expired": str(expired),
        "Signature": signature,
    }

    for key, value in params.items():
        all_params[key] = str(value)

    sorted_params = sorted(all_params.items(), key=lambda x: x[0])
    query_string = "&".join(f"{k}={v}" for k, v in sorted_params)

    return f"wss://tts.cloud.tencent.com/stream_wsv2?{query_string}"
